FROM php:8.2-fpm-alpine

ARG user
ARG uid

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

RUN apk update && apk add \
  bash \
  curl \
  libpng-dev \
  libxml2-dev \
  zip \
  unzip \
  shadow  # Add shadow package to install useradd

RUN docker-php-ext-install pdo pdo_mysql \
  && apk --no-cache add nodejs npm

# Composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/local/bin/composer

#USER root

#RUN chmod 777 -R /var/www/

RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

#entrypoint
ENTRYPOINT ["entrypoint.sh"]
WORKDIR /var/www

CMD ["php-fpm"]
