name: laravel
services:
  mysql:
    container_name: mysql
    image: mysql/mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - .docker/db/data:/var/lib/mysql:Z
      - .docker/logs:/var/log/mysql:Z
      - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - .docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      bridge:
  # ####################################################################################################
  # # DATABASE (MariaDB)
  # ####################################################################################################
  # db:
  #     image: mariadb:10.11
  #     ports:
  #         - 3306:3306
  #     volumes:
  #         - .docker/db/data:/var/lib/mysql
  #         - .docker/logs:/var/log/mysql
  #         - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
  #         - .docker/db/sql:/docker-entrypoint-initdb.d
  #     environment:
  #         MYSQL_ROOT_PASSWORD: root
  #         MYSQL_DATABASE: laravel_db_name
  #         MYSQL_USER: laravel_db_user
  #         MYSQL_PASSWORD: laravel_db_pass
  #  networks:
  #    bridge:
  ####################################################################################################
  # phpMyAdmin
  ####################################################################################################
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    linked_to:
      - mysql
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    volumes:
      - .docker/phpmyadmin/sessions:/sessions:Z
    networks:
      bridge:
  ####################################################################################################
  # Adminer
  ####################################################################################################
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 7070:8080
    depends_on:
      - mysql
    networks:
      bridge:

# Networks
networks:
  bridge:
    driver: bridge
