name: laravel
services:
  ####################################################################################################
  # PHP
  ####################################################################################################
  php:
    container_name: php
    build: .docker/php
    ports:
      - 5173:5173
    volumes:
      - .:/var/www:cached

  ####################################################################################################
  # Nginx
  ####################################################################################################
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  ####################################################################################################
  # DATABASE (MySQL)
  ####################################################################################################
  db:
    container_name: db
    image: mysql:8.1
    ports:
      - 3306:3306
    volumes:
      - .docker/db/data:/var/lib/mysql
      - .docker/logs:/var/log/mysql
      - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - .docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laraveldb
      MYSQL_USER: larauser
      MYSQL_PASSWORD: larapass

  ####################################################################################################
  # phpMyAdmin
  ####################################################################################################
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    volumes:
      - .docker/phpmyadmin/sessions:/sessions:Z

  ####################################################################################################
  # Adminer
  ####################################################################################################
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 7070:8080
    depends_on:
      - db

  ####################################################################################################
  # Mailpit
  ####################################################################################################
  mail:
    container_name: mailpit
    image: axllent/mailpit:latest
    ports:
      - 8025:8025
      - 1025:1025

  ####################################################################################################
  # Redis
  ####################################################################################################
  redis:
    container_name: redis
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - .docker/redis/data:/data
    ports:
      - 6379:6379

  # ####################################################################################################
  # # DATABASE (MariaDB)
  # ####################################################################################################
  # db:
  #     image: mariadb:10.11
  #     ports:
  #         - 3306:3306
  #     volumes:
  #         - .container/db/data:/var/lib/mysql
  #         - .container/logs:/var/log/mysql
  #         - .container/db/my.cnf:/etc/mysql/conf.d/my.cnf
  #         - .container/db/sql:/docker-entrypoint-initdb.d
  #     environment:
  #         MYSQL_ROOT_PASSWORD: root
  #         MYSQL_DATABASE: laraveldb
  #         MYSQL_USER: larauser
  #         MYSQL_PASSWORD: larapass

  ####################################################################################################
  # PostgreSQL
  ####################################################################################################
  # db:
  #     image: postgres:16
  #     ports:
  #         - 5432:5432
  #     volumes:
  #         - .container/db/data:/var/lib/postgresql/data
  #         - .container/db/sql:/docker-entrypoint-initdb.d
  #     environment:
  #         - POSTGRES_USER=larauser
  #         - POSTGRES_PASSWORD=larapass
  #         - POSTGRES_DB=laraveldb

  ####################################################################################################
  # pgAdmin
  ####################################################################################################
  # pgadmin:
  #     image: dpage/pgadmin4
  #     ports:
  #         - 5050:80
  #     environment:
  #         - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #         - PGADMIN_DEFAULT_PASSWORD=password
  #     depends_on:
  #         - db
