services:
  ####################################################################################################
  # app
  ####################################################################################################
  app:
    build:
      args:
        user: developer
        uid: 1000
      context: ./container/php/
      dockerfile: Containerfile
    image: web
    container_name: web
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: laravel.test
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
      - ~/.ssh:/root/.ssh
    depends_on:
      - db
      - redis
    networks:
      - laravel

  ####################################################################################################
  # DATABASE (MySQL)
  ####################################################################################################
  db:
    image: mysql:8.1
    container_name: dbms
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - ./container/mysql/sql:/docker-entrypoint-initdb.d
    networks:
      - laravel
  ####################################################################################################
  # Nginx
  ####################################################################################################
  nginx:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ./src:/var/www
      - ./container/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./container/nginx/ssl:/etc/nginx/ssl
      - ./container/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

    ####################################################################################################
    # phpMyAdmin
    ####################################################################################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    ports:
      - 8080:80
    depends_on:
      - db
    restart: unless-stopped
    environment:
      PMA_HOST: db
      #PMA_USER: ${DB_USERNAME}
      #PMA_PASSWORD: ${DB_PASSWORD}
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - laravel

  ####################################################################################################
  # Redis
  ####################################################################################################
  redis:
    image: 'redis:alpine'
    container_name: cachedb
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
    ports:
      - '6379:6379'
    networks:
      - laravel
networks:
  laravel:
    driver: bridge
