################### VOLUMES ####################
#volumes:
#  volumes:
#    dbcache:
#    db:
################### NETWORK ####################
networks:
  backend:
    name: backend
    driver: bridge
  frontend:
    name: frontend
    driver: bridge
################### SERVICE ####################
services:
  # MySQL ######################################
  db:
    image: mysql:8.1
    container_name: mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql:Z
      - ./logs/mysql:/var/log/mysql:Z
      - ./container/mysql/sql:/docker-entrypoint-initdb.d:Z
    networks:
      - backend
  # Redis ######################################
  redis:
    image: 'redis:alpine'
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./data/redis:/data:Z
    ports:
      - '6379:6379'
    networks:
      - backend
  # PHPMyAdmin #################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - db
    restart: unless-stopped
    environment:
      PMA_HOST: db
      #PMA_USER: ${DB_USERNAME}
      #PMA_PASSWORD: ${DB_PASSWORD}
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - backend
      - frontend
  # Adminer ####################################
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8081:8080
    depends_on:
      - db
    networks:
      - backend
      - frontend
  # Mail #######################################
  mail:
    image: axllent/mailpit:latest
    container_name: mail
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - backend
      - frontend
  # Minio #####################################
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - 9000:9000
      - 8900:8900
    environment:
      MINIO_ROOT_USER: sail
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./data/minio:/data:z
    networks:
      - backend
      - frontend
  # MariaDB ###################################
  # db:
  #   image: mariadb:10.11
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - .docker/db/data:/var/lib/mysql
  #     - .docker/logs:/var/log/mysql
  #     - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
  #     - .docker/db/sql:/docker-entrypoint-initdb.d
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: laravel_db_name
  #     MYSQL_USER: laravel_db_user
  #     MYSQL_PASSWORD: laravel_db_pass
  #   networks:
  #     - backend
  # PostgreSQL #################################
  # db:
  #   image: postgres:16
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - .docker/db/data:/var/lib/postgresql/data
  #     - .docker/db/sql:/docker-entrypoint-initdb.d
  #   environment:
  #     - POSTGRES_USER=refactorian
  #     - POSTGRES_PASSWORD=refactorian
  #     - POSTGRES_DB=refactorian
  #   networks:
  #     - backend
  # pgAdmin ####################################
  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - 5050:80
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=password
  #   depends_on:
  #     - db
  #   networks:
  #     - backend
  #     - frontend
  # php-fpm ########################################
  php-fpm:
    build:
      args:
        user: developer
        uid: 1000
      context: ./container/php/
      dockerfile: Containerfile
    image: php-fpm
    container_name: php-fpm
    restart: unless-stopped
    expose:
      - 9000
    working_dir: /var/www/
    volumes:
      - ./src:/var/www:cached,z
    depends_on:
      - db
      - redis
    networks:
      - backend
  # Nginx ######################################
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www:z
      - ./container/nginx/default.conf:/etc/nginx/conf.d/default.conf:z
      - ./container/nginx/nginx.conf:/etc/nginx/nginx.conf:z
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend
