name: laravel
services:
  ####################################################################################################
  # PHP
  ####################################################################################################
  php:
    container_name: php
    build: .docker/php
    ports:
      - 5173:5173
    volumes:
      - .:/var/www:cached
    networks:
      lara-net:
  ####################################################################################################
  # Nginx
  ####################################################################################################
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      lara-net:
  ####################################################################################################
  # DATABASE (MySQL)
  ####################################################################################################
  db:
    container_name: db
    image: mysql:8.1
    ports:
      - 3306:3306
    volumes:
      - .docker/db/data:/var/lib/mysql:Z
      - .docker/logs:/var/log/mysql:Z
      - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - .docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: refactorian
      MYSQL_USER: refactorian
      MYSQL_PASSWORD: refactorian
    networks:
      lara-net:
  # ####################################################################################################
  # # DATABASE (MariaDB)
  # ####################################################################################################
  # db:
  #     image: mariadb:10.11
  #     ports:
  #         - 3306:3306
  #     volumes:
  #         - .docker/db/data:/var/lib/mysql
  #         - .docker/logs:/var/log/mysql
  #         - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
  #         - .docker/db/sql:/docker-entrypoint-initdb.d
  #     environment:
  #         MYSQL_ROOT_PASSWORD: root
  #         MYSQL_DATABASE: laravel_db_name
  #         MYSQL_USER: laravel_db_user
  #         MYSQL_PASSWORD: laravel_db_pass
  #  networks:
  #    lara-net:
  ####################################################################################################
  # phpMyAdmin
  ####################################################################################################
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    linked_to:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    volumes:
      - .docker/phpmyadmin/sessions:/sessions:Z
    networks:
      lara-net:
  ####################################################################################################
  # Adminer
  ####################################################################################################
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 7070:8080
    depends_on:
      - db
    networks:
      lara-net:
  ####################################################################################################
  # Mailpit
  ####################################################################################################
  mail:
    container_name: mailpit
    image: axllent/mailpit:latest
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      lara-net:
  ####################################################################################################
  # Redis
  ####################################################################################################
  redis:
    container_name: redis
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - .docker/redis/data:/data
    ports:
      - 6379:6379
    networks:
      lara-net:
# Networks
networks:
  lara-net:
    driver: bridge