apiVersion: v1
kind: Pod
metadata:
  name: laravel
  labels:
    app: laravel
spec:
  volumes:
    - name: workdir
      hostPath:
        path: ./src
        type: DirectoryOrCreate
  containers:
    - name: swole
      image: swole:latest
      ports:
        - containerPort: 1215
        - hostPort: 1215
      volumeMounts:
        - name: workdir
          mountPath: /var/www/html:Z
#    - name: node
#      image: node:20.19.2-alpine
#      ports:
#        - containerPort: 3000
#      volumeMounts:
#        - name: workdir
#          mountPath: /var/www
