FROM php:8.2-fpm-alpine

# Work in the specific space
WORKDIR /var/www/html

# Install dependencies
RUN apk add --no-cache freetype libpng libjpeg-turbo freetype-dev libpng-dev libjpeg-turbo-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg

RUN NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) && \
    docker-php-ext-install -j${NPROC} gd 

RUN apk del --no-cache freetype-dev libpng-dev libjpeg-turbo-dev

# Install extensions
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/bin/
RUN install-php-extensions gd curl json mbstring pdo_mysql xml zip bcmath iconv

# Install swoole
RUN apk add --no-cache libstdc++ supervisor nano unzip ${PHPIZE_DEPS} \
    && pecl install openswoole \
    && docker-php-ext-enable openswoole \
    && apk del ${PHPIZE_DEPS}

COPY ./supervisor.conf /etc/supervisor/conf.d/supervisor.conf
COPY ./supervisord.conf /etc/supervisor/supervisord.conf

# Composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/local/bin/composer

ENV COMPOSER_ALLOW_SUPERUSER 1
ENV COMPOSER_HOME /composer
ENV PATH $PATH:/composer/vendor/bin
RUN composer config --global process-timeout 3600

COPY ./run.sh /tmp/
#ENTRYPOINT ["/tmp/run.sh"]
