FROM php:8.2-fpm-alpine

WORKDIR /var/www
COPY php.ini /usr/local/etc/php/
COPY custom.conf /usr/local/etc/php-fpm.d/custom.conf
COPY .bashrc /root/

RUN apk add --no-cache \
      bash \
      build-base \
      zlib-dev \
      mysql-client \
      curl \
      gnupg \
      procps \
      vim \
      git \
      unzip \
      zip \
      postgresql-libs \
      postgresql-dev \
      libzip-dev

RUN docker-php-ext-install -j$(nproc) zip pdo_mysql pdo_pgsql pgsql

RUN apk add --no-cache icu-dev \
  && docker-php-ext-configure intl \
  && docker-php-ext-install intl

# redis
RUN pecl install redis && docker-php-ext-enable redis

# pcov
RUN pecl install pcov && docker-php-ext-enable pcov

# Composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/local/bin/composer

ENV COMPOSER_ALLOW_SUPERUSER 1
ENV COMPOSER_HOME /composer
ENV PATH $PATH:/composer/vendor/bin
RUN composer config --global process-timeout 3600
RUN composer global require "laravel/installer"

EXPOSE 5173
